### ISSUE TITLE
Precedence issue with $SHELL, no 'tcsh' love

### ISSUE THREAD

**Issue by pryankster** [Perl-Toolchain-Gang/local-lib#5]
guess_shell will warn with unassigned variable warnings if $SHELL is not set.

Also, if $SHELL is 'tcsh', you get 'sh' style output instead of 'csh' style

Suggested fix:

```sub guess_shelltype {
  my $shellbin
    = defined $ENV{SHELL}
      ? ($ENV{SHELL} =~ /([\w.]+)$/)[-1]
    : ( ( $^O eq 'MSWin32' && exists $ENV{'!EXITCODE'} )
      ? 'bash'
    : ( ( $^O eq 'MSWin32' && $ENV{PROMPT} && $ENV{COMSPEC} )
      ? ($ENV{COMSPEC} =~ /([\w.]+)$/)[-1]
    : ( ( $^O eq 'MSWin32' && !$ENV{PROMPT} )
      ? 'powershell.exe'
    : 'sh' )));

  for ($shellbin) {
    return
        /t?csh$/                 ? 'csh'
      : /fish$/                  ? 'fish'
      : /command(?:\.com)?$/i    ? 'cmd'
      : /cmd(?:\.exe)?$/i        ? 'cmd'
      : /4nt(?:\.exe)?$/i        ? 'cmd'
      : /powershell(?:\.exe)?$/i ? 'powershell'
                                 : 'bourne';
  }
}
```

**Comment by haarg** [comment]
I don't see how tcsh would end up giving sh style output, and the tests confirm that.  The match isn't anchored at the start, so the `t?` doesn't have any effect.

The problem isn't with an unassigned SHELL variable, but with an empty string value.  I've fixed it by adding a length check (efc117423b3dfa8536cf19a00d4e13edfb5e552c).
