### ISSUE TITLE
2.000022 failing tests for perl-5.8.9

### ISSUE THREAD

**Issue by peterharrison** [Perl-Toolchain-Gang/local-lib#7]
When installing local::lib over our suite of perl versions, the latest version of local::lib is failing for perl-5.8.9.

Output from the tests is attached.
[local_lib_fail.txt](https://github.com/Perl-Toolchain-Gang/local-lib/files/1056865/local_lib_fail.txt)

**Comment by karenetheridge** [comment]
This is fixed in 2.000023.
